** --------------------------------------------------------------------.
* This command file was generated by paneldata.org                    .
* --------------------------------------------------------------------.
* !!! I M P O R T A N T - W A R N I N G !!!                           .
* You alone are responsible for contents and appropriate.             .
* usage by accepting the usage agreement.                             .
* --------------------------------------------------------------------.
* Please report any errors of the code generated here                 .
* to soepmail@diw.de                                                  .
* --------------------------------------------------------------------.



* * * LOCAL VARIABLES * * *

global MY_PATH_IN   "C:/Users/laura/Desktop/SocialHousing/data/SOEPdata/rawdata/"
global GEO_PATH_IN "C:/Users/laura/Desktop/SocialHousing/data/SOEPdata/rawdata/"
global MY_PATH_OUT  "C:/Users/laura/Desktop/SocialHousing/data/SOEPdata/databearbeitet/"
global MY_FILE_OUT  ${MY_PATH_OUT}soep_all.dta
global MY_LOG_FILE  ${MY_PATH_OUT}new.log
capture log close
log using "${MY_LOG_FILE}", text replace
set more off


** * * NOT PROCESSED * * *.
* From datasets 'hl': ['hlf0074_h', 'hlf0011_h', 'hlc0005_h', 'hlf0019_h', 'hlf0011_v5', 'hlf0186', 'hlc0111_h'].
* From datasets 'pequiv': ['l11102', 'e11102', 'i11107', 'i11103', 'p11101', 'fjob1', 'd11101', 'w11102', 'fopery', 'd11106', 'i11101', 'i11102', 'd11107'].
* From datasets 'ggkbou': ['bgtyp'].
* From datasets 'pl': ['plh0177'].


/*
* * * PFAD * * *

use fhhnr uhhnr binetto bepop persnr hhnr nhhnr bcnetto bghhnr enetto cnetto qnetto onetto gnetto shhnr rnetto mpop hnetto ahhnr fnetto nnetto thhnr snetto ipop bdnetto bchhnr bfpop xpop kpop bhpop whhnr opop inetto rhhnr lhhnr ehhnr anetto fpop upop dnetto xhhnr tpop bihhnr bpop yhhnr vhhnr epop vnetto ypop hhhnr bhhnr qhhnr ynetto ghhnr xnetto zpop pnetto bdpop ohhnr behhnr bgnetto mhhnr jpop unetto lnetto mnetto apop chhnr knetto gpop qpop znetto psample wpop bbnetto dpop khhnr bhhhnr bbhhnr bgpop sex phhnr bdhhnr bnetto gebjahr benetto ihhnr banetto hpop lpop bbpop npop bfhhnr rpop bahhnr bcpop bapop cpop jhhnr jnetto bhnetto vpop dhhnr spop bfnetto zhhnr ppop bipop wnetto tnetto /// 
using "${MY_PATH_IN}ppfad.dta", clear


* * * BALANCED VS UNBALANCED * * *

keep if ( (knetto >= 10 & knetto < 20) | (dnetto >= 10 & dnetto < 20) | (nnetto >= 10 & nnetto < 20) | (bhnetto >= 10 & bhnetto < 20) | (bbnetto >= 10 & bbnetto < 20) | (hnetto >= 10 & hnetto < 20) | (ynetto >= 10 & ynetto < 20) | (inetto >= 10 & inetto < 20) | (bcnetto >= 10 & bcnetto < 20) | (pnetto >= 10 & pnetto < 20) | (qnetto >= 10 & qnetto < 20) | (wnetto >= 10 & wnetto < 20) | (bfnetto >= 10 & bfnetto < 20) | (banetto >= 10 & banetto < 20) | (unetto >= 10 & unetto < 20) | (fnetto >= 10 & fnetto < 20) | (rnetto >= 10 & rnetto < 20) | (cnetto >= 10 & cnetto < 20) | (benetto >= 10 & benetto < 20) | (bdnetto >= 10 & bdnetto < 20) | (binetto >= 10 & binetto < 20) | (gnetto >= 10 & gnetto < 20) | (anetto >= 10 & anetto < 20) | (tnetto >= 10 & tnetto < 20) | (xnetto >= 10 & xnetto < 20) | (bgnetto >= 10 & bgnetto < 20) | (mnetto >= 10 & mnetto < 20) | (bnetto >= 10 & bnetto < 20) | (snetto >= 10 & snetto < 20) | (enetto >= 10 & enetto < 20) | (jnetto >= 10 & jnetto < 20) | (vnetto >= 10 & vnetto < 20) | (onetto >= 10 & onetto < 20) | (znetto >= 10 & znetto < 20) | (lnetto >= 10 & lnetto < 20) )


* * * ONLY PRIVATE HOUSEHOLDS * * *

keep if ( (kpop == 1 | kpop == 2) | (dpop == 1 | dpop == 2) | (npop == 1 | npop == 2) | (bhpop == 1 | bhpop == 2) | (bbpop == 1 | bbpop == 2) | (hpop == 1 | hpop == 2) | (ypop == 1 | ypop == 2) | (ipop == 1 | ipop == 2) | (bcpop == 1 | bcpop == 2) | (ppop == 1 | ppop == 2) | (qpop == 1 | qpop == 2) | (wpop == 1 | wpop == 2) | (bfpop == 1 | bfpop == 2) | (bapop == 1 | bapop == 2) | (upop == 1 | upop == 2) | (fpop == 1 | fpop == 2) | (rpop == 1 | rpop == 2) | (cpop == 1 | cpop == 2) | (bepop == 1 | bepop == 2) | (bdpop == 1 | bdpop == 2) | (bipop == 1 | bipop == 2) | (gpop == 1 | gpop == 2) | (apop == 1 | apop == 2) | (tpop == 1 | tpop == 2) | (xpop == 1 | xpop == 2) | (bgpop == 1 | bgpop == 2) | (mpop == 1 | mpop == 2) | (bpop == 1 | bpop == 2) | (spop == 1 | spop == 2) | (epop == 1 | epop == 2) | (jpop == 1 | jpop == 2) | (vpop == 1 | vpop == 2) | (opop == 1 | opop == 2) | (zpop == 1 | zpop == 2) | (lpop == 1 | lpop == 2) )


* * * GENDER ( male = 1 / female = 2) * * *

/* all genders */


* * * SAVE PFAD * * *

save "${MY_PATH_OUT}pfad.dta", replace 
clear


* * * HRF * * *

use bcphrf zphrf bgphrf bdphrf fphrf bfphrf kphrf rphrf uphrf wphrf iphrf persnr hhnr biphrf sphrf vphrf tphrf lphrf bhphrf prgroup nphrf xphrf mphrf ophrf ephrf cphrf bphrf bbphrf pphrf yphrf gphrf bephrf baphrf aphrf hphrf qphrf dphrf jphrf /// 
using "${MY_PATH_IN}phrf.dta" 
save "${MY_PATH_OUT}hrf.dta", replace 
clear

*/
* * * CREATE MASTER * * *

use "${MY_PATH_IN}pfad.dta", clear
merge 1:1 persnr hhnr using "${MY_PATH_IN}hrf.dta", keep(master match) nogen
save "${MY_PATH_OUT}master.dta", replace


* * * READ DATA * * *
***********************************************************************************
***********************************************************************************
********HOUSEHOLD LEVEL DATA*******************************************************

use ah14 ah4201 ah09 ah23 ah16 ahhnr using "${MY_PATH_IN}ah.dta", clear
save "${MY_PATH_OUT}ah.dta", replace

use bh14b bhhnr bh3601 bh12b bh18b bh09b bh07g using "${MY_PATH_IN}bh.dta", clear
save "${MY_PATH_OUT}bh.dta", replace

use chhnr ch18b ch29b ch21b ch15g ch16g ch25b ch4801 ch23b using "${MY_PATH_IN}ch.dta", clear
save "${MY_PATH_OUT}ch.dta", replace

use dhhnr dh16g dh15g dh29b dh18b dh4801 dh21b dh23b dh25b using "${MY_PATH_IN}dh.dta", clear
save "${MY_PATH_OUT}dh.dta", replace

use eh16b eh07g eh06g eh14b eh09b eh12b eh20b ehhnr eh3901 using "${MY_PATH_IN}eh.dta", clear
save "${MY_PATH_OUT}eh.dta", replace

use fh09b fh20b fh06g fh16b fh07g fh3901 fh14b fh12b fhhnr using "${MY_PATH_IN}fh.dta", clear
save "${MY_PATH_OUT}fh.dta", replace

use gh3901 gh07g gh12b gh09b gh20b gh06g gh16b gh14b ghhnr using "${MY_PATH_IN}gh.dta", clear
save "${MY_PATH_OUT}gh.dta", replace

use hh15 hh0402 hh11 hh10 hhhnr hh13 hh48 hh19 hh20 hh2601 hh16 using "${MY_PATH_IN}hh.dta", clear
save "${MY_PATH_OUT}hh.dta", replace

use ih10 ihhnr ih49 ih16 ih2601 ih20 ih19 ih0402 ih11a ih12 ih4201 ih15 using "${MY_PATH_IN}ih.dta", clear
save "${MY_PATH_OUT}ih.dta", replace

use jh19 jh10 jh20 jhhnr jh11a jh49 jh4201 jh12 jh0402 jh16 jh15 jh2601 using "${MY_PATH_IN}jh.dta", clear
save "${MY_PATH_OUT}jh.dta", replace

use kh11a kh10 kh2601 kh15 kh16 khhnr kh12 kh4201 kh20 kh0402 kh19 kh49 using "${MY_PATH_IN}kh.dta", clear
save "${MY_PATH_OUT}kh.dta", replace

use lh10 lh2601 lh50 lh23a lh16 lh12 lh4201 lh19 lh11a lh0402 lh15 lhhnr lh20 using "${MY_PATH_IN}lh.dta", clear
save "${MY_PATH_OUT}lh.dta", replace

use mh50 mh12 mh2701 mh01 mh20 mh11a mhhnr mh4201 mh16 mh19 mh0502 mh24 mh15 using "${MY_PATH_IN}mh.dta", clear
save "${MY_PATH_OUT}mh.dta", replace

***So far I only start using data from 97 onwards (cause of reporting of social housing)

use nh24 nh4201 nh20 nhhnr nh19 nh2701 nh0502 nh15 nh16 nh11a nh01 nh12 nh50 nh34 nh38 nh2901 nh11b nh1306 nh1307 using "${MY_PATH_IN}nh.dta", clear
save "${MY_PATH_OUT}nh.dta", replace

use oh15 oh11c oh12 oh11a ohhnr oh16 oh0502 oh2701 oh4201 oh50 oh01 oh34 oh38 oh2901 oh11b oh13* using "${MY_PATH_IN}oh.dta", clear
save "${MY_PATH_OUT}oh.dta", replace

use ph13 ph22 ph4201 ph0502 ph50 ph04 ph16 ph2601 phhnr ph25 ph24 ph36 ph38 ph2801 ph17 ph14* using "${MY_PATH_IN}ph.dta", clear
save "${MY_PATH_OUT}ph.dta", replace

use qh1408 qh0502 qh15 qh04 qh13 qh21 qh24 qh35 qhhnr qh23 qh54 qh2501 qh4201 qh35 qh37 qh2701 qh16 qh14* using "${MY_PATH_IN}qh.dta", clear
save "${MY_PATH_OUT}qh.dta", replace

use rh24 rh0502 rh15 rh5315 rh23 rh04 rh49 rh4201 rh13 rh21 rh2501 rhhnr rh35 rh37 rh2701 rh16 rh14* using "${MY_PATH_IN}rh.dta", clear
save "${MY_PATH_OUT}rh.dta", replace

use shhnr sh0402 sh2501 sh13 sh4201 sh24 sh10 sh4901 sh11 sh23 sh08 sh35 sh37 sh2701 sh12 sh09* using "${MY_PATH_IN}sh.dta", clear
save "${MY_PATH_OUT}sh.dta", replace

use th12 th22 th2301 th09 th5113 th11 thhnr th4001 th14 th0402 th4801 th2501 th33 th2501 th13 th10* using "${MY_PATH_IN}th.dta", clear
save "${MY_PATH_OUT}th.dta", replace

use uh0402 uh11 uh4801 uh22 uh09 uhhnr uh4001 uh12 uh2301 uh14 uh33 uh2501 uh13 uh1006 uh1007 uh10* using "${MY_PATH_IN}uh.dta", clear
save "${MY_PATH_OUT}uh.dta", replace

use vhhnr vh0402 vh5101 vh2201 vh09 vh08 vh5415 vh21 vh10 vh3901 vh12 vh32 vh34 vh2401 vh11 vh14* using "${MY_PATH_IN}vh.dta", clear
save "${MY_PATH_OUT}vh.dta", replace

use wh3901 wh08 whhnr wh0402 wh5101 wh09 wh21 wh10 wh2201 wh12 wh32 wh34 wh2401 wh11 wh14* using "${MY_PATH_IN}wh.dta", clear
save "${MY_PATH_OUT}wh.dta", replace

use xh10 xh09 xh0402 xh12 xh2201 xhhnr xh5101 xh5513 xh0801 xh3901 xh21 xh32 xh34 xh2401 xh11 xh14* using "${MY_PATH_IN}xh.dta", clear
save "${MY_PATH_OUT}xh.dta", replace

use yh4001 yh12 yhhnr yh5201 yh09 yh0402 yh21 yh0801 yh10 yh2301 yh22 yh33 yh35 yh25 yh11 yh14* using "${MY_PATH_IN}yh.dta", clear
save "${MY_PATH_OUT}yh.dta", replace

use zh2301 zh0801 zh09 zh10 zh0402 zh21 zh12 zh4001 zh5201 zhhnr zh22 zh33 zh35 zh25 zh11 zh14* using "${MY_PATH_IN}zh.dta", clear
save "${MY_PATH_OUT}zh.dta", replace

use bahhnr bah0801 bah09 bah0402 bah21 bah12 bah10 bah2301 bah22 bah5201 bah4001 bah33 bah35 bah2501 bah2503 bah11 bah14* using "${MY_PATH_IN}bah.dta", clear
save "${MY_PATH_OUT}bah.dta", replace

use bbh4001 bbh09 bbh12 bbh21 bbh2301 bbh0801 bbh22 bbh5101 bbh0402 bbh10 bbhhnr bbh5513 bbh33 bbh35 bbh2501 bbh2503 bbh11 bbh14* using "${MY_PATH_IN}bbh.dta", clear
save "${MY_PATH_OUT}bbh.dta", replace

use bch21 bch5101 bch0402 bchhnr bch0801 bch09 bch2301 bch12 bch10 bch22 bch4001 bch33 bch35 bch2501 bch2503 bch11 bch14* using "${MY_PATH_IN}bch.dta", clear
save "${MY_PATH_OUT}bch.dta", replace

use bdh0801 bdhhnr bdh10 bdh0402 bdh22 bdh5101 bdh5518 bdh21 bdh09 bdh12 bdh4001 bdh2301 bdh33 bdh35 bdh2501 bdh2503 bdh11 bdh14* using "${MY_PATH_IN}bdh.dta", clear
save "${MY_PATH_OUT}bdh.dta", replace

use beh2401 beh09 beh22 behhnr beh23 beh4301 beh07 beh5401 beh06 beh36 beh38 beh2501 beh2601 beh08 beh11* using "${MY_PATH_IN}beh.dta", clear
save "${MY_PATH_OUT}beh.dta", replace

use bfh11 bfh3901 bfh0701 bfh09 bfh32 bfh0202 bfhhnr bfh5215 bfh3401 bfh13 bfh4901 bfh10 bfh12 bfh2003 bfh2012 bfh20* using "${MY_PATH_IN}bfh.dta", clear
save "${MY_PATH_OUT}bfh.dta", replace

use bgh11 bghhnr bgh7405 bgh31 bgh09 bgh32 bgh08 bgh3401 bgh6801 bgh48 bgh05 bgh0202 bgh2501 bgh3601 bgh3801 bgh10 bgh41 bgh12* using "${MY_PATH_IN}bgh.dta", clear
save "${MY_PATH_OUT}bgh.dta", replace

use bhh_28 bhh_11 bhh_10 bhh_61_01 bhh_27 bhh_13 bhh_30_01 bhhhnr bhh_07 bhh_02_02 bhh_41 bhh_66_05 bhh_25_01 bhh_32_01 bhh_34_01 bhh_12 bhh_14* using "${MY_PATH_IN}bhh.dta", clear
save "${MY_PATH_OUT}bhh.dta", replace

use bih_08 bihhnr bih_05 bih_27 bih_61_01 bih_11 bih_67_05 bih_30_01 bih_28 bih_41 bih_09 bih_02_02 bih_25_01 bih_32_01 bih_34_01 bih_10 bih_14* using "${MY_PATH_IN}bih.dta", clear
save "${MY_PATH_OUT}bih.dta", replace






***********************************************************************************
***********************************************************************************
********PEQUIV FIles**************************************************************


use e1110284 i1110384 i1110284 persnr opery84 w1110284 i1110584 d1110684 d1110784 p1110184 i1110784 i1110184 d1110184 i1120584 l1110284 using "${MY_PATH_IN}apequiv.dta", clear
save "${MY_PATH_OUT}apequiv.dta", replace

use l1110285 i1110185 p1110185 d1110685 persnr d1110185 i1110585 i1110385 e1110285 i1110285 opery85 w1110285 i1120585 i1110785 d1110785 using "${MY_PATH_IN}bpequiv.dta", clear
save "${MY_PATH_OUT}bpequiv.dta", replace

use d1110186 e1110286 i1110286 i1110586 d1110686 persnr i1110186 i1110386 i1120586 d1110786 w1110286 i1110786 l1110286 opery86 p1110186 using "${MY_PATH_IN}cpequiv.dta", clear
save "${MY_PATH_OUT}cpequiv.dta", replace

use e1110287 persnr d1110787 l1110287 i1110287 w1110287 i1110387 i1110187 i1120587 i1110787 i1110587 opery87 d1110687 p1110187 d1110187 using "${MY_PATH_IN}dpequiv.dta", clear
save "${MY_PATH_OUT}dpequiv.dta", replace

use d1110688 i1110288 persnr w1110288 p1110188 l1110288 i1110188 i1110588 i1110788 d1110788 d1110188 i1110388 opery88 i1120588 e1110288 using "${MY_PATH_IN}epequiv.dta", clear
save "${MY_PATH_OUT}epequiv.dta", replace

use p1110189 i1120589 i1110289 persnr i1110189 d1110789 i1110589 w1110289 opery89 l1110289 d1110189 i1110389 e1110289 i1110789 d1110689 using "${MY_PATH_IN}fpequiv.dta", clear
save "${MY_PATH_OUT}fpequiv.dta", replace

use p1110190 e1110290 d1110190 i1110790 persnr i1110590 opery90 i1110390 i1120590 i1110290 l1110290 w1110290 i1110190 d1110690 d1110790 using "${MY_PATH_IN}gpequiv.dta", clear
save "${MY_PATH_OUT}gpequiv.dta", replace

use i1110791 d1110191 i1110591 persnr opery91 i1120591 i1110191 l1110291 e1110291 p1110191 d1110791 d1110691 i1110291 i1110391 w1110291 using "${MY_PATH_IN}hpequiv.dta", clear
save "${MY_PATH_OUT}hpequiv.dta", replace

use d1110192 i1110392 d1110792 i1110592 persnr i1110292 opery92 l1110292 p1110192 i1120592 i1110792 d1110692 i1110192 e1110292 w1110292 using "${MY_PATH_IN}ipequiv.dta", clear
save "${MY_PATH_OUT}ipequiv.dta", replace

use i1110793 e1110293 d1110793 persnr l1110293 i1110593 opery93 w1110293 i1110393 d1110193 d1110693 i1110193 i1110293 i1120593 p1110193 using "${MY_PATH_IN}jpequiv.dta", clear
save "${MY_PATH_OUT}jpequiv.dta", replace

use i1110594 e1110294 i1110194 i1110794 persnr p1110194 d1110694 i1110294 d1110194 l1110294 i1120594 d1110794 w1110294 i1110394 opery94 using "${MY_PATH_IN}kpequiv.dta", clear
save "${MY_PATH_OUT}kpequiv.dta", replace

use persnr i1110395 i1120595 d1110695 e1110295 p1110195 w1110295 d1110195 i1110795 i1110295 d1110795 l1110295 i1110595 i1110195 opery95 using "${MY_PATH_IN}lpequiv.dta", clear
save "${MY_PATH_OUT}lpequiv.dta", replace

use i1110796 d1110196 d1110796 persnr w1110296 i1110296 l1110296 i1110196 i1110596 e1110296 p1110196 i1110396 d1110696 i1120596 opery96 using "${MY_PATH_IN}mpequiv.dta", clear
save "${MY_PATH_OUT}mpequiv.dta", replace

use w1110297 d1110197 i1110597 persnr p1110197 i1110797 d1110697 d1110797 i1110397 e1110297 i1110197 l1110297 i1110297 i1120597 opery97 using "${MY_PATH_IN}npequiv.dta", clear
save "${MY_PATH_OUT}npequiv.dta", replace

use i1110198 d1110798 persnr p1110198 i1110398 i1110298 opery98 w1110298 d1110198 i1110598 i1120598 l1110298 i1110798 e1110298 d1110698 using "${MY_PATH_IN}opequiv.dta", clear
save "${MY_PATH_OUT}opequiv.dta", replace

use i1110299 i1110599 w1110299 persnr d1110199 opery99 e1110299 i1110399 d1110699 l1110299 i1120599 p1110199 i1110799 d1110799 i1110199 using "${MY_PATH_IN}ppequiv.dta", clear
save "${MY_PATH_OUT}ppequiv.dta", replace

use p1110100 i1110300 i1110200 persnr d1110700 i1120500 opery00 l1110200 w1110200 d1110100 i1110100 i1110500 d1110600 e1110200 i1110700 using "${MY_PATH_IN}qpequiv.dta", clear
save "${MY_PATH_OUT}qpequiv.dta", replace

use p1110101 i1110101 i1110701 persnr w1110201 i1110301 d1110101 i1110501 i1120501 l1110201 opery01 d1110701 d1110601 i1110201 e1110201 using "${MY_PATH_IN}rpequiv.dta", clear
save "${MY_PATH_OUT}rpequiv.dta", replace

use i1110102 d1110602 i1110302 i1110202 d1110702 persnr i1110502 i1110702 d1110102 e1110202 opery02 p1110102 w1110202 i1120502 l1110202 using "${MY_PATH_IN}spequiv.dta", clear
save "${MY_PATH_OUT}spequiv.dta", replace

use d1110103 i1110303 d1110603 persnr l1110203 p1110103 e1110203 i1110503 i1110103 i1120503 d1110703 i1110203 opery03 w1110203 i1110703 using "${MY_PATH_IN}tpequiv.dta", clear
save "${MY_PATH_OUT}tpequiv.dta", replace

use w1110204 i1110704 d1110104 d1110604 persnr i1110504 i1120504 p1110104 opery04 l1110204 e1110204 d1110704 i1110304 i1110204 i1110104 using "${MY_PATH_IN}upequiv.dta", clear
save "${MY_PATH_OUT}upequiv.dta", replace

use d1110105 i1110305 w1110205 p1110105 persnr e1110205 i1110505 i1110705 opery05 i1120505 l1110205 i1110205 i1110105 d1110705 d1110605 using "${MY_PATH_IN}vpequiv.dta", clear
save "${MY_PATH_OUT}vpequiv.dta", replace

use i1110506 d1110706 p1110106 l1110206 d1110106 persnr i1110106 w1110206 i1110306 i1120506 i1110706 d1110606 e1110206 i1110206 opery06 using "${MY_PATH_IN}wpequiv.dta", clear
save "${MY_PATH_OUT}wpequiv.dta", replace

use w1110207 i1110507 i1120507 d1110107 persnr d1110707 d1110607 l1110207 e1110207 i1110307 i1110107 p1110107 i1110707 i1110207 opery07 using "${MY_PATH_IN}xpequiv.dta", clear
save "${MY_PATH_OUT}xpequiv.dta", replace

use e1110208 i1120508 persnr d1110608 opery08 p1110108 d1110708 l1110208 i1110108 i1110708 d1110108 w1110208 i1110508 i1110308 i1110208 using "${MY_PATH_IN}ypequiv.dta", clear
save "${MY_PATH_OUT}ypequiv.dta", replace

use e1110209 d1110609 i1120509 d1110109 persnr i1110309 i1110709 opery09 p1110109 i1110109 d1110709 i1110209 l1110209 w1110209 i1110509 using "${MY_PATH_IN}zpequiv.dta", clear
save "${MY_PATH_OUT}zpequiv.dta", replace


use i1110310 d1110110 l1110210 i1110510 i1110210 persnr i1110710 opery10 w1110210 e1110210 p1110110 i1120510 d1110710 i1110110 d1110610 using "${MY_PATH_IN}bapequiv.dta", clear
save "${MY_PATH_OUT}bapequiv.dta", replace

use i1110711 i1110211 i1110311 i1110511 persnr w1110211 d1110111 l1110211 p1110111 i1120511 i1110111 e1110211 d1110711 opery11 d1110611 using "${MY_PATH_IN}bbpequiv.dta", clear
save "${MY_PATH_OUT}bbpequiv.dta", replace

use i1110712 e1110212 i1110212 w1110212 persnr i1110312 opery12 p1110112 d1110712 i1110112 d1110612 i1120512 i1110512 d1110112 l1110212 using "${MY_PATH_IN}bcpequiv.dta", clear
save "${MY_PATH_OUT}bcpequiv.dta", replace

use i1110213 i1110313 d1110713 i1110113 i1110713 opery13 persnr l1110213 p1110113 d1110613 e1110213 i1120513 w1110213 d1110113 i1110513 using "${MY_PATH_IN}bdpequiv.dta", clear
save "${MY_PATH_OUT}bdpequiv.dta", replace

use w1110214 i1110114 d1110714 opery14 i1110314 persnr i1120514 i1110514 i1110214 e1110214 d1110114 i1110714 l1110214 p1110114 d1110614 using "${MY_PATH_IN}bepequiv.dta", clear
save "${MY_PATH_OUT}bepequiv.dta", replace

use i1110115 w1110215 i1110315 persnr d1110615 i1110715 d1110715 i1120515 p1110115 i1110215 l1110215 i1110515 opery15 e1110215 d1110115 using "${MY_PATH_IN}bfpequiv.dta", clear
save "${MY_PATH_OUT}bfpequiv.dta", replace

use i1110316 d1110716 i1110116 opery16 persnr p1110116 w1110216 i1110216 i1110716 e1110216 l1110216 d1110616 i1110516 i1120516 d1110116 using "${MY_PATH_IN}bgpequiv.dta", clear
save "${MY_PATH_OUT}bgpequiv.dta", replace

use i1110217 l1110217 p1110117 i1110517 w1110217 d1110617 opery17 persnr i1120517 i1110117 i1110717 i1110317 e1110217 d1110117 d1110717 using "${MY_PATH_IN}bhpequiv.dta", clear
save "${MY_PATH_OUT}bhpequiv.dta", replace

use d1110618 persnr using "${MY_PATH_IN}bipequiv.dta", clear
save "${MY_PATH_OUT}bipequiv.dta", replace


**********************************************************************************
**********************************************************************************
***********PERSONAL FILES*********************************************************
use ap0303 persnr using "${MY_PATH_IN}ap.dta", clear
save "${MY_PATH_OUT}ap.dta", replace

use persnr bp0103 using "${MY_PATH_IN}bp.dta", clear
save "${MY_PATH_OUT}bp.dta", replace

use cp0103 persnr using "${MY_PATH_IN}cp.dta", clear
save "${MY_PATH_OUT}cp.dta", replace

use dp0104 persnr using "${MY_PATH_IN}dp.dta", clear
save "${MY_PATH_OUT}dp.dta", replace

use ep0103 persnr using "${MY_PATH_IN}ep.dta", clear
save "${MY_PATH_OUT}ep.dta", replace

use fp0103 persnr using "${MY_PATH_IN}fp.dta", clear
save "${MY_PATH_OUT}fp.dta", replace

use gp0103 persnr using "${MY_PATH_IN}gp.dta", clear
save "${MY_PATH_OUT}gp.dta", replace

use hp1006 persnr using "${MY_PATH_IN}hp.dta", clear
save "${MY_PATH_OUT}hp.dta", replace

use ip9806 persnr using "${MY_PATH_IN}ip.dta", clear
save "${MY_PATH_OUT}ip.dta", replace

use jp0106 persnr using "${MY_PATH_IN}jp.dta", clear
save "${MY_PATH_OUT}jp.dta", replace

use kp0106 persnr using "${MY_PATH_IN}kp.dta", clear
save "${MY_PATH_OUT}kp.dta", replace

use persnr lp0105 using "${MY_PATH_IN}lp.dta", clear
save "${MY_PATH_OUT}lp.dta", replace

use persnr mp0105 using "${MY_PATH_IN}mp.dta", clear
save "${MY_PATH_OUT}mp.dta", replace

use np0105 persnr using "${MY_PATH_IN}np.dta", clear
save "${MY_PATH_OUT}np.dta", replace

use op0105 persnr using "${MY_PATH_IN}op.dta", clear
save "${MY_PATH_OUT}op.dta", replace

use pp0105 persnr using "${MY_PATH_IN}pp.dta", clear
save "${MY_PATH_OUT}pp.dta", replace

use qp0105 persnr using "${MY_PATH_IN}qp.dta", clear
save "${MY_PATH_OUT}qp.dta", replace

use rp0105 persnr using "${MY_PATH_IN}rp.dta", clear
save "${MY_PATH_OUT}rp.dta", replace

use sp0105 persnr using "${MY_PATH_IN}sp.dta", clear
save "${MY_PATH_OUT}sp.dta", replace

use tp0105 persnr using "${MY_PATH_IN}tp.dta", clear
save "${MY_PATH_OUT}tp.dta", replace

use persnr up0107 using "${MY_PATH_IN}up.dta", clear
save "${MY_PATH_OUT}up.dta", replace

use vp0106 persnr using "${MY_PATH_IN}vp.dta", clear
save "${MY_PATH_OUT}vp.dta", replace

use wp0106 persnr using "${MY_PATH_IN}wp.dta", clear
save "${MY_PATH_OUT}wp.dta", replace

use xp0106 persnr using "${MY_PATH_IN}xp.dta", clear
save "${MY_PATH_OUT}xp.dta", replace

use yp0108 persnr using "${MY_PATH_IN}yp.dta", clear
save "${MY_PATH_OUT}yp.dta", replace

use zp0107 persnr using "${MY_PATH_IN}zp.dta", clear
save "${MY_PATH_OUT}zp.dta", replace



use bap0107 persnr using "${MY_PATH_IN}bap.dta", clear
save "${MY_PATH_OUT}bap.dta", replace

use bbp0107 persnr using "${MY_PATH_IN}bbp.dta", clear
save "${MY_PATH_OUT}bbp.dta", replace

use bcp0107 persnr using "${MY_PATH_IN}bcp.dta", clear
save "${MY_PATH_OUT}bcp.dta", replace

use bdp0107 persnr using "${MY_PATH_IN}bdp.dta", clear
save "${MY_PATH_OUT}bdp.dta", replace

use bep0107 persnr using "${MY_PATH_IN}bep.dta", clear
save "${MY_PATH_OUT}bep.dta", replace

use bfp0107 persnr using "${MY_PATH_IN}bfp.dta", clear
save "${MY_PATH_OUT}bfp.dta", replace

use bgp0107 persnr using "${MY_PATH_IN}bgp.dta", clear
save "${MY_PATH_OUT}bgp.dta", replace

use bhp_01_07 persnr using "${MY_PATH_IN}bhp.dta", clear
save "${MY_PATH_OUT}bhp.dta", replace

use bip_01_07 persnr using "${MY_PATH_IN}bip.dta", clear
save "${MY_PATH_OUT}bip.dta", replace





********************************************************************************
********************************************************************************
*******************GEMEINDEINDKATOREN*******************************************


use gh10e gh1902e gh16e gh14e ghhnr using "${MY_PATH_IN}ghost.dta", clear
save "${MY_PATH_OUT}ghost.dta", replace

use gp5506e persnr using "${MY_PATH_IN}gpost.dta", clear
save "${MY_PATH_OUT}gpost.dta", replace

use "$GEO_PATH_IN\ggkbou.dta"
duplicates drop hhnr, force
save "${MY_PATH_OUT}ggkbou.dta", replace

use behhgr behhnr using "${MY_PATH_IN}behbrutto.dta", clear
save "${MY_PATH_OUT}behbrutto.dta", replace
















* * * MERGE DATA * * *

use   "${MY_PATH_OUT}master.dta", clear
merge m:1 hhnr using "${MY_PATH_OUT}ggkbou.dta", keep(master match) nogen
merge m:1 thhnr using "${MY_PATH_OUT}th.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}xp.dta", keep(master match) nogen
merge m:1 whhnr using "${MY_PATH_OUT}wh.dta", keep(master match) nogen
merge m:1 chhnr using "${MY_PATH_OUT}ch.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}ypequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}spequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}npequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bpequiv.dta", keep(master match) nogen
merge m:1 lhhnr using "${MY_PATH_OUT}lh.dta", keep(master match) nogen
merge m:1 nhhnr using "${MY_PATH_OUT}nh.dta", keep(master match) nogen
merge m:1 hhhnr using "${MY_PATH_OUT}hh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}qpequiv.dta", keep(master match) nogen
merge m:1 ohhnr using "${MY_PATH_OUT}oh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bcpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}zpequiv.dta", keep(master match) nogen
merge m:1 bhhhnr using "${MY_PATH_OUT}bhh.dta", keep(master match) nogen
merge m:1 jhhnr using "${MY_PATH_OUT}jh.dta", keep(master match) nogen
merge m:1 yhhnr using "${MY_PATH_OUT}yh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}xpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}fpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}mpequiv.dta", keep(master match) nogen
merge m:1 bbhhnr using "${MY_PATH_OUT}bbh.dta", keep(master match) nogen
merge m:1 phhnr using "${MY_PATH_OUT}ph.dta", keep(master match) nogen
merge m:1 vhhnr using "${MY_PATH_OUT}vh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}jpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}lpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}ppequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}hpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}apequiv.dta", keep(master match) nogen
merge m:1 bhhnr using "${MY_PATH_OUT}bh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}upequiv.dta", keep(master match) nogen
merge m:1 ghhnr using "${MY_PATH_OUT}ghost.dta", keep(master match) nogen
merge m:1 rhhnr using "${MY_PATH_OUT}rh.dta", keep(master match) nogen
merge m:1 ghhnr using "${MY_PATH_OUT}gh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}wpequiv.dta", keep(master match) nogen
merge m:1 uhhnr using "${MY_PATH_OUT}uh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bgpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}vpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bdpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}opequiv.dta", keep(master match) nogen
merge m:1 bihhnr using "${MY_PATH_OUT}bih.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}epequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bbpequiv.dta", keep(master match) nogen
merge m:1 bghhnr using "${MY_PATH_OUT}bgh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}dpequiv.dta", keep(master match) nogen
merge m:1 zhhnr using "${MY_PATH_OUT}zh.dta", keep(master match) nogen
merge m:1 shhnr using "${MY_PATH_OUT}sh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}jp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bapequiv.dta", keep(master match) nogen
merge m:1 bdhhnr using "${MY_PATH_OUT}bdh.dta", keep(master match) nogen
merge m:1 bchhnr using "${MY_PATH_OUT}bch.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}tpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}ipequiv.dta", keep(master match) nogen
merge m:1 bahhnr using "${MY_PATH_OUT}bah.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bepequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}kpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bfp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bfpequiv.dta", keep(master match) nogen
merge m:1 khhnr using "${MY_PATH_OUT}kh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}gpequiv.dta", keep(master match) nogen
merge m:1 fhhnr using "${MY_PATH_OUT}fh.dta", keep(master match) nogen
merge m:1 qhhnr using "${MY_PATH_OUT}qh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}rpequiv.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}ip.dta", keep(master match) nogen
merge m:1 ahhnr using "${MY_PATH_OUT}ah.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bhpequiv.dta", keep(master match) nogen
merge m:1 dhhnr using "${MY_PATH_OUT}dh.dta", keep(master match) nogen
merge m:1 ihhnr using "${MY_PATH_OUT}ih.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}yp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bp.dta", keep(master match) nogen
merge m:1 bfhhnr using "${MY_PATH_OUT}bfh.dta", keep(master match) nogen
merge m:1 mhhnr using "${MY_PATH_OUT}mh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}ep.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}cpequiv.dta", keep(master match) nogen
merge m:1 behhnr using "${MY_PATH_OUT}beh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}op.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}mp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}kp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}zp.dta", keep(master match) nogen
merge m:1 ehhnr using "${MY_PATH_OUT}eh.dta", keep(master match) nogen
merge m:1 xhhnr using "${MY_PATH_OUT}xh.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}pp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}cp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}wp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bgp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bhp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}gp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bap.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bdp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bcp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}gpost.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bep.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}ap.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}np.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}vp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bipequiv.dta", keep(master match) nogen
merge m:1 behhnr using "${MY_PATH_OUT}behbrutto.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bip.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}tp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}lp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}dp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}up.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}qp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}fp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}rp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}sp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}hp.dta", keep(master match) nogen
merge 1:1 persnr using "${MY_PATH_OUT}bbp.dta", keep(master match) nogen


* * * DONE * * *

label data "paneldata.org"
save "${MY_FILE_OUT}", replace
desc

log close
