** --------------------------------------------------------------------.
* This command file was generated by paneldata.org                    .
* --------------------------------------------------------------------.
* !!! I M P O R T A N T - W A R N I N G !!!                           .
* You alone are responsible for contents and appropriate.             .
* usage by accepting the usage agreement.                             .
* --------------------------------------------------------------------.
* Please report any errors of the code generated here                 .
* to soepmail@diw.de                                                  .
* --------------------------------------------------------------------.



* * * LOCAL VARIABLES * * *

global MY_PATH_IN   "/home/larnemann/soep-data/soep.v36/stata/raw/"
global GEO_PATH_IN "/home/larnemann/soep-data/soep.v36/stata/"
global MY_PATH_OUT  "/home/larnemann/work/2021-11-11_2/Soep_15_11_21/"
global MY_FILE_OUT  ${MY_PATH_OUT}data/soep_all.dta
global MY_LOG_FILE  ${MY_PATH_OUT}new.log
capture log close
log using "${MY_LOG_FILE}", text replace
set more off


** * * NOT PROCESSED * * *.
* From datasets 'hl': ['hlf0074_h', 'hlf0011_h', 'hlc0005_h', 'hlf0019_h', 'hlf0011_v5', 'hlf0186', 'hlc0111_h'].
* From datasets 'pequiv': ['l11102', 'e11102', 'i11107', 'i11103', 'p11101', 'fjob1', 'd11101', 'w11102', 'fopery', 'd11106', 'i11101', 'i11102', 'd11107'].
* From datasets 'ggkbou': ['bgtyp'].
* From datasets 'pl': ['plh0177'].



* * * PFAD * * *

use fhhnr uhhnr binetto bepop persnr hhnr nhhnr bcnetto bghhnr enetto cnetto qnetto onetto gnetto shhnr rnetto mpop hnetto ahhnr fnetto nnetto thhnr snetto ipop bdnetto bchhnr bfpop xpop kpop bhpop whhnr opop inetto rhhnr lhhnr ehhnr anetto fpop upop dnetto xhhnr tpop bihhnr bpop yhhnr vhhnr epop vnetto ypop hhhnr bhhnr qhhnr ynetto ghhnr xnetto zpop pnetto bdpop ohhnr behhnr bgnetto mhhnr jpop unetto lnetto mnetto apop chhnr knetto gpop qpop znetto psample wpop bbnetto dpop khhnr bhhhnr bbhhnr bgpop sex phhnr bdhhnr bnetto gebjahr benetto ihhnr banetto hpop lpop bbpop npop bfhhnr rpop bahhnr bcpop bapop cpop jhhnr jnetto bhnetto vpop dhhnr spop bfnetto zhhnr ppop bipop wnetto tnetto using "${MY_PATH_IN}ppfad.dta", clear

/*
* * * BALANCED VS UNBALANCED * * *

keep if ( (knetto >= 10 & knetto < 20) | (dnetto >= 10 & dnetto < 20) | (nnetto >= 10 & nnetto < 20) | (bhnetto >= 10 & bhnetto < 20) | (bbnetto >= 10 & bbnetto < 20) | (hnetto >= 10 & hnetto < 20) | (ynetto >= 10 & ynetto < 20) | (inetto >= 10 & inetto < 20) | (bcnetto >= 10 & bcnetto < 20) | (pnetto >= 10 & pnetto < 20) | (qnetto >= 10 & qnetto < 20) | (wnetto >= 10 & wnetto < 20) | (bfnetto >= 10 & bfnetto < 20) | (banetto >= 10 & banetto < 20) | (unetto >= 10 & unetto < 20) | (fnetto >= 10 & fnetto < 20) | (rnetto >= 10 & rnetto < 20) | (cnetto >= 10 & cnetto < 20) | (benetto >= 10 & benetto < 20) | (bdnetto >= 10 & bdnetto < 20) | (binetto >= 10 & binetto < 20) | (gnetto >= 10 & gnetto < 20) | (anetto >= 10 & anetto < 20) | (tnetto >= 10 & tnetto < 20) | (xnetto >= 10 & xnetto < 20) | (bgnetto >= 10 & bgnetto < 20) | (mnetto >= 10 & mnetto < 20) | (bnetto >= 10 & bnetto < 20) | (snetto >= 10 & snetto < 20) | (enetto >= 10 & enetto < 20) | (jnetto >= 10 & jnetto < 20) | (vnetto >= 10 & vnetto < 20) | (onetto >= 10 & onetto < 20) | (znetto >= 10 & znetto < 20) | (lnetto >= 10 & lnetto < 20) )

*/
* * * ONLY PRIVATE HOUSEHOLDS * * *

keep if ( (kpop == 1 | kpop == 2) | (dpop == 1 | dpop == 2) | (npop == 1 | npop == 2) | (bhpop == 1 | bhpop == 2) | (bbpop == 1 | bbpop == 2) | (hpop == 1 | hpop == 2) | (ypop == 1 | ypop == 2) | (ipop == 1 | ipop == 2) | (bcpop == 1 | bcpop == 2) | (ppop == 1 | ppop == 2) | (qpop == 1 | qpop == 2) | (wpop == 1 | wpop == 2) | (bfpop == 1 | bfpop == 2) | (bapop == 1 | bapop == 2) | (upop == 1 | upop == 2) | (fpop == 1 | fpop == 2) | (rpop == 1 | rpop == 2) | (cpop == 1 | cpop == 2) | (bepop == 1 | bepop == 2) | (bdpop == 1 | bdpop == 2) | (bipop == 1 | bipop == 2) | (gpop == 1 | gpop == 2) | (apop == 1 | apop == 2) | (tpop == 1 | tpop == 2) | (xpop == 1 | xpop == 2) | (bgpop == 1 | bgpop == 2) | (mpop == 1 | mpop == 2) | (bpop == 1 | bpop == 2) | (spop == 1 | spop == 2) | (epop == 1 | epop == 2) | (jpop == 1 | jpop == 2) | (vpop == 1 | vpop == 2) | (opop == 1 | opop == 2) | (zpop == 1 | zpop == 2) | (lpop == 1 | lpop == 2) )


* * * GENDER ( male = 1 / female = 2) * * *

/* all genders */


* * * SAVE PFAD * * *

save "${MY_PATH_OUT}pfad.dta", replace 
clear

* * * HRF * * *

use bcphrf zphrf bgphrf bdphrf fphrf bfphrf kphrf rphrf uphrf wphrf iphrf persnr hhnr biphrf sphrf vphrf tphrf lphrf bhphrf prgroup nphrf xphrf mphrf ophrf ephrf cphrf bphrf bbphrf pphrf yphrf gphrf bephrf baphrf aphrf hphrf qphrf dphrf jphrf /// 
using "${MY_PATH_IN}phrf.dta" 
save "${MY_PATH_OUT}hrf.dta", replace 
clear


* * * CREATE MASTER * * *

use "${MY_PATH_OUT}pfad.dta", clear
merge 1:1 persnr hhnr using "${MY_PATH_OUT}hrf.dta", keep(master match) nogen
save "${MY_PATH_OUT}master.dta", replace
